# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_auto_20181011_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
