# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-24 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0003_auto_20181024_1113'),
        ('appointment', '0006_auto_20181022_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='client',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clientserviceslot',
            name='client',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='provider_type',
        ),
        migrations.RemoveField(
            model_name='providerassign',
            name='client_service_slot',
        ),
        migrations.RemoveField(
            model_name='providerassign',
            name='edit_user',
        ),
        migrations.RemoveField(
            model_name='providerassign',
            name='provider_available_slot',
        ),
        migrations.RemoveField(
            model_name='providerassignactionlog',
            name='statable',
        ),
        migrations.RemoveField(
            model_name='providerassignactionlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='provideravailableslot',
            name='provider',
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.ProviderType'),
        ),
        migrations.AlterField(
            model_name='appointmentusertimeslot',
            name='provider_available_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.ProviderAvailableSlot'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.Client'),
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRM.Provider'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientServiceSlot',
        ),
        migrations.DeleteModel(
            name='ClientType',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='ProviderAssign',
        ),
        migrations.DeleteModel(
            name='ProviderAssignActionLog',
        ),
        migrations.DeleteModel(
            name='ProviderAvailableSlot',
        ),
        migrations.DeleteModel(
            name='ProviderType',
        ),
    ]
