# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-20 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRM', '0019_auto_20181219_1514'),
        ('appointment', '0012_auto_20181129_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='provider_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_provider_assign', to='HRM.ProviderAssign'),
        ),
    ]
