# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0013_appointmentusertimeslot_provider_assign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel', models.CharField(blank=True, default='', max_length=13, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ลูกค้า, ...',
            },
        ),
        migrations.AddField(
            model_name='serviceappointment',
            name='customer',
            field=models.ManyToManyField(related_name='customer', to='appointment.Customer'),
        ),
    ]
