# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-04 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0014_auto_20190104_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='customer',
            field=models.ManyToManyField(blank=True, to='appointment.Customer'),
        ),
    ]
