# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-08 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0015_auto_20190104_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceappointment',
            name='customer',
        ),
    ]
