# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-08 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0016_remove_serviceappointment_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
