# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0017_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='appointmenttype',
            name='provider_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HRM.ProviderType'),
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttype',
            unique_together=set([]),
        ),
    ]
