# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-18 12:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0018_auto_20190109_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app', to='appointment.Appointment'),
        ),
    ]
