# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-31 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0020_auto_20190130_1606'),
        ('appointment', '0020_auto_20190123_1648'),
    ]

    operations = [
    ]
