# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-14 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRM', '0028_auto_20190114_1142'),
        ('appointment', '0025_appointmentusertimeslot_service_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwapShiftBroadcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('status', his.framework.models.fields._StatableStatusField(default=0, editable=False)),
                ('edit_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('source_provider_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_pa', to='HRM.ProviderAssign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SwapShiftBroadcastActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('statable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='appointment.SwapShiftBroadcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
