# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def remove_swap_shift_broadcast(apps, schema_editor):
    SwapShiftBroadcast = apps.get_model("appointment", "SwapShiftBroadcast")
    Message = apps.get_model("sqool", "Message")
    Message.objects.filter(content_type='swap').delete()
    SwapShiftBroadcast.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0029_pre'),
        ('sqool', '0007_auto_20190419_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.Provider'),
            preserve_default=False,
        ),
        migrations.RunPython(remove_swap_shift_broadcast),
        migrations.AlterField(
            model_name='swapshiftbroadcast',
            name='source_provider_assign',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source_pa', to='appointment.ProviderAssign'),
            preserve_default=False,
        ),
    ]
