# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-26 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0030_auto_20190426_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentusertimeslot',
            name='provider_assigns',
            field=models.ManyToManyField(blank=True, related_name='app_provider_assign', to='appointment.ProviderAssign'),
        ),
    ]
