# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 11:37
from __future__ import unicode_literals

from django.db import migrations, models


def update_permission_contenttype(apps, schema_editor, reverse=False):
    from django.contrib.contenttypes.models import ContentType
    HISPermission = apps.get_model('users', 'HISPermission')
    if reverse:
        oldtype = 'hispermission'
        try:
            newtype = ContentType.objects.get(app_label='users', model='HISPermission')
        except ContentType.DoesNotExist:
            return
    else:
        oldtype = 'HISPermission'
        try:
            newtype = ContentType.objects.get(app_label='users', model='hispermission')
        except ContentType.DoesNotExist:
            return
    HISPermission.objects.filter(content_type__model=oldtype).update(content_type=newtype)


def reverse_permission_contenttype(apps, schema_editor):
    update_permission_contenttype(apps, schema_editor, reverse=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hispermission',
            name='type',
            field=models.IntegerField(choices=[(1, 'MANAGEMENT'), (2, 'SCREEN'), (3, 'RESOURCE'), (4, 'ACTION'), (5, 'CUSTOM')], default=2),
        ),
        migrations.RunPython(update_permission_contenttype, reverse_code=reverse_permission_contenttype),
    ]
