# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:59
from __future__ import unicode_literals

from django.db import migrations
import his.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170824_1137'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('active_users', his.users.models.ActiveUserManager()),
                ('objects', his.users.models.AllUserManager()),
            ],
        ),
    ]
