# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170906_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
