# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170906_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='station_no',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
