# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_device_station_no'),
        ('users', '0004_position_code'),
    ]

    operations = [
    ]
