# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_position_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('licence', models.CharField(blank=True, max_length=20)),
                ('personnel_no', models.CharField(blank=True, max_length=20)),
                ('citizen_no', models.CharField(blank=True, max_length=20)),
                ('job_description', models.CharField(blank=True, max_length=200)),
                ('flag_start_date', models.DateField()),
                ('flag_end_date', models.DateField()),
                ('status', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('birth_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('organization_level', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, null=True)),
                ('jc_code', models.CharField(blank=True, max_length=20)),
                ('telephone_1', models.CharField(blank=True, max_length=20)),
                ('telephone_2', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('organization_parent', his.framework.models.fields.SelfReferenceForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Position'),
        ),
    ]
