# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_miscellaneousorder_eligibility_type'),
        ('users', '0008_auto_20171106_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
    ]
