# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 16:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_level',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_parent',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
        ),
    ]
