# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_device_station_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pre_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อ'),
        ),
    ]
