# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20171219_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.IntegerField(choices=[(1, 'GENERAL'), (2, 'DOCTOR'), (3, 'PHARMACIST'), (4, 'REGISTERED_NURSE'), (5, 'ADMIT_STAFF')], default=1),
        ),
    ]
