# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-18 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20180403_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttype',
            name='page_size',
            field=models.CharField(blank=True, help_text='Page sizing of report', max_length=50),
        ),
    ]
