# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180515_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doctor/images/'),
        ),
    ]
