# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20180927_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printserver',
            name='url',
            field=models.URLField(help_text='Example<br/>                                                      Jasper : http://192.168.56.150:9080/printserver/print<br/>                                                      MSWord : http://192.168.56.154/api/print'),
        ),
    ]
