# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20180928_1457'),
        ('users', '0018_user_image'),
    ]

    operations = [
    ]
