# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_duty_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='duty',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_info', to='users.Duty'),
        ),
    ]
