# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-16 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20181108_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeinfo',
            name='sub_division',
        ),
    ]
