# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_remove_employeeinfo_sub_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_experince_year', models.IntegerField(help_text='Example: อายุงานไม่เกิน 6 ปี สามารถลาพักร้อนได้ 6 วัน', verbose_name='อายุงานไม่เกิน x ปี')),
                ('day_off', models.IntegerField(default=1, verbose_name='จำนวนวันที่ลาพักร้อนได้')),
            ],
            options={
                'verbose_name': 'กำหนดจำนวนวันลาพักร้อน',
            },
        ),
    ]
