# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-20 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_annualleave'),
        ('users', '0020_merge_20181119_1001'),
    ]

    operations = [
    ]
