# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userfcmtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'ordering': ('display_seq', 'id')},
        ),
        migrations.AddField(
            model_name='duty',
            name='display_seq',
            field=models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ'),
        ),
    ]
