# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_userfcmtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfcmtoken',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfcmtoken',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
