# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-16 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190114_1040'),
        ('users', '0030_auto_20190116_1619'),
    ]

    operations = [
    ]
