# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-20 14:03
from __future__ import unicode_literals

from django.db import migrations, models
import his.users.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20190220_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='facebook_access_token',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_expires',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='facebook_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=his.users.models.utils.UploadToDir('uploaded/profile'), verbose_name='Profile image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='isDisplay_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_visit_follow_page',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='url_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
