# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-25 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190220_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='email_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='OTP email matching key'),
        ),
    ]
