# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190220_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_alias',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
