# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-26 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_userotp_email_key'),
        ('users', '0035_userprofile_user_alias'),
    ]

    operations = [
    ]
