# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-29 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_merge_20190326_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='code',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
