# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190329_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', help_text="user's middle name", max_length=150, verbose_name='middle name'),
        ),
    ]
