# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-11 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_userprofile_middle_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDefaultRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('roles', models.ManyToManyField(blank=True, to='users.Role')),
            ],
            options={
                'verbose_name': 'Application Default Role',
                'verbose_name_plural': 'Application Default Role',
            },
        ),
    ]
