# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-26 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_applicationdefaultrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationdefaultrole',
            options={'ordering': ('id',), 'verbose_name': 'Application Default Role', 'verbose_name_plural': 'Application Default Roles'},
        ),
    ]
