# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-07 10:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20190426_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.Patient'),
        ),
    ]
