# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_userprofile_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDeviceSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.BooleanField(default=True)),
                ('chat', models.BooleanField(default=True)),
                ('device', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_setting', to='users.MobileDevice')),
            ],
            options={
                'verbose_name': 'device setting',
                'verbose_name_plural': 'devices setting',
            },
        ),
    ]
