# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 16:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rolegroup'),
        ('users', '0041_auto_20190517_1627'),
    ]

    operations = [
    ]
