# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-24 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_auto_20190517_1627'),
        ('users', '0042_mobiledevicesetting'),
    ]

    operations = [
    ]
