# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import his.framework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_merge_20190624_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='extra',
            field=models.TextField(default='{}', help_text='must be in JSON format', validators=[his.framework.validators.json_text_validator], verbose_name='extra json info'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='extra',
            field=models.TextField(default='{}', help_text='must be in JSON format', validators=[his.framework.validators.json_text_validator], verbose_name='extra json info'),
        ),
    ]
