# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_merge_20190821_1657'),
        ('users', '0044_auto_20190819_1137'),
    ]

    operations = [
    ]
