# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-28 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0175_merge_20190822_1007'),
        ('users', '0045_merge_20190822_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Nationality'),
        ),
    ]
