# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-04 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_userprofile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(1, 'REGISTER'), (2, 'ADD_OPTION'), (3, 'COMPLETE')], default=1, help_text="REGISTER after created account but didn't set password yet, ADD_OPTION after set password but no profile, COMPLETE after set profile.", verbose_name='state'),
        ),
    ]
