# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields
import his.framework.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('owner_name', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ชื่อ-สกุล')),
                ('relative', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='ความสัมพันธ์')),
                ('no', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('town', models.CharField(blank=True, default='', max_length=50)),
                ('street', models.CharField(blank=True, default='', max_length=100)),
                ('road', models.CharField(blank=True, max_length=100)),
                ('tel_home', models.CharField(blank=True, default='', max_length=12)),
                ('tel_home_suffix', models.CharField(blank=True, default='', max_length=6)),
                ('tel_office', models.CharField(blank=True, default='', max_length=12)),
                ('tel_office_suffix', models.CharField(blank=True, default='', max_length=6)),
                ('tel_mobile', models.CharField(blank=True, default='', max_length=12)),
                ('email', models.EmailField(blank=True, default='', max_length=50)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('channel', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillDisplayName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'ordering': ['display_seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name_en', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=10)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClinicalTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('A', 'อาการเบื้องต้น'), ('B', 'จุดสังเกต'), ('C', 'แพ้ยา'), ('D', 'โรคประจำตัว'), ('E', 'เหตุผลเปลี่ยนชื่อ'), ('F', 'ความสัมพันธ์'), ('G', 'เหตุผลยกเลิกนามแฝง'), ('H', 'สภาพผู้ป่วยก่อนจำหน่าย'), ('I', 'Discharge Status')], max_length=3)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('require_flag', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('iso', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=50)),
                ('name_en_big', models.CharField(max_length=50)),
                ('num_code', models.CharField(max_length=50)),
                ('phone_code', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['display_seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='รหัสสิทธิหลัก')),
                ('name', models.CharField(max_length=200, verbose_name='ชื่อสิทธิ (ภาษาไทย)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='ชื่อสิทธิ (ภาษาอังกฤษ)')),
                ('type', his.framework.models.fields.EnumField(default=10, enum=[(1, 'EMERGENCY'), (2, 'ACCIDENT'), (3, 'REFER'), (4, 'PROJECT'), (5, 'HANDICAP'), (6, 'DISCOUNT_POLICY'), (7, 'DISCOUNT_CARD'), (10, 'UNDEFINED')], verbose_name='ประเภทสิทธิ์')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('group_number', models.CharField(blank=True, help_text='เลขกลุ่มสิทธิ์ เพื่อใช้ป้องกันเลือกสิทธิ์ซ้ำ\nเว้นว่างไว้ถ้าไม่ต้องการ lock', max_length=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name_en', models.CharField(max_length=40)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name_en', models.CharField(blank=True, max_length=500, verbose_name='ชื่อหน่วยงานภาษาอังกฤษ')),
                ('type', his.framework.models.fields.EnumField(default=1, enum=[(1, 'GENERAL'), (2, 'BILLING'), (3, 'DRUG'), (4, 'SUPPLY'), (5, 'TREATMENT'), (6, 'SPECIMEN_COLLECTOR'), (7, 'CLINIC'), (8, 'PREMIUM_CLINIC')], verbose_name='ประเภทหน่วยงาน')),
            ],
            options={
                'abstract': False,
                'ordering': ('-is_active', 'display_seq'),
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('code', models.CharField(help_text='รหัสแพทย์', max_length=10)),
                ('first_name', models.CharField(max_length=80, verbose_name='ชื่อ')),
                ('first_name_en', models.CharField(blank=True, default='', max_length=80, verbose_name='ชื่อภาษาอังกฤษ')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อกลาง')),
                ('middle_name_en', models.CharField(blank=True, default='', max_length=80, verbose_name='ชื่อกลางภาษาอังกฤษ')),
                ('last_name', models.CharField(max_length=80, verbose_name='นามสกุล')),
                ('last_name_en', models.CharField(blank=True, default='', max_length=80, verbose_name='นามสกุลภาษาอังกฤษ')),
                ('certificate_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='เลขที่ใบประกอบวิชาชีพเวชกรรม')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', his.framework.models.fields.EnumField(default=5, enum=[(1, 'APPOINTMENT'), (2, 'PENDING'), (3, 'PERFORMED'), (4, 'CANCEL'), (5, 'DRAFT')], verbose_name='สถานะของคำสั่ง')),
                ('order_payment_status', his.framework.models.fields.EnumField(default=1, enum=[(1, 'PENDING'), (2, 'READY'), (3, 'PAID')], verbose_name='สถานะการชำระเงิน')),
                ('order_type', his.framework.models.fields.EnumField(default=1, enum=[(1, 'DIRECT'), (2, 'VERBAL'), (3, 'TELEPHONE')], verbose_name='ชนิดคำสั่ง')),
                ('order_time', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่สั่ง')),
                ('order_receive_time', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่รับคำสั่งแทน')),
                ('order_approve_time', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาที่ยืนยันคำสั่งแทน')),
                ('order_perform_time', models.DateTimeField(blank=True, null=True, verbose_name='เวลาเริ่มทำ')),
            ],
            options={
                'verbose_name': 'คำสั่งแพทย์',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('print_api', models.CharField(blank=True, max_length=500, verbose_name='url of document print api')),
                ('jasper_path', models.CharField(blank=True, max_length=255, verbose_name='Path ไปยังไฟล์ jasper')),
                ('version', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'ordering': ['display_seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('status', his.framework.models.fields._StatableStatusField(default=0, editable=False)),
                ('number', models.CharField(default='', max_length=12)),
                ('type', models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('SS', 'Short Stay'), ('ER', 'ER')], max_length=4)),
                ('remark', models.CharField(blank=True, help_text='จุดสังเกต', max_length=255)),
                ('drug_allergy', models.CharField(blank=True, help_text='แพ้ยา', max_length=255, null=True)),
                ('other_allergy', models.CharField(blank=True, help_text='แพ้อื่น ๆ', max_length=255, null=True)),
                ('underlying_disease', models.CharField(blank=True, help_text='โรคประจำตัว', max_length=255)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField(blank=True, null=True)),
                ('triage_level', models.CharField(blank=True, max_length=3, verbose_name='ระดับการคัดกรอง')),
                ('chief_complaints', models.CharField(blank=True, help_text='อาการเบื่องต้น', max_length=255)),
                ('discharge_note', models.CharField(blank=True, help_text='รายละเอียดการ Discharge', max_length=255)),
                ('is_appointment', models.BooleanField(default=False, help_text='encounter ที่เปิดจากการนัดหมาย')),
                ('queue_date', models.DateField(auto_now_add=True, help_text='ใช้สำหรับจัดเรียงคิว')),
                ('queue_time', models.TimeField(blank=True, help_text='หากเป็นนัดหมายจะเป็นเวลาที่นัดหมาย                                                หากไม่ใช่จะเป็น 11.30 สำหรับ walk-in เช้า                                                และ 15.30 สำหรับ walk-in บ่าย', null=True)),
                ('hospital_fee_charged', models.BooleanField(default=False, help_text='คิดค่าเหยียบโรงบาลแล้ว?')),
                ('clinic_type', models.CharField(choices=[('RGL', 'Regular'), ('SPC', 'Special'), ('PRM', 'Premium')], default='RGL', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', his.framework.models.fields.EnumField(enum=[(1, 'OPD_NEW'), (2, 'OPD_TRIAGE'), (3, 'OPD_ARRIVE'), (4, 'OPD_SCREEN'), (5, 'OPD_QUEUE_EXAM'), (6, 'OPD_CHECK_IN'), (7, 'OPD_CHECK_OUT'), (8, 'OPD_DISCHARGE'), (9, 'OPD_PAID'), (10, 'OPD_DISPENSE'), (11, 'OPD_SEND_LAB'), (12, 'OPD_SEND_TREATMENT'), (13, 'OPD_EDIT'), (14, 'OPD_REFILL'), (101, 'ADMISSION_ADMIT'), (102, 'ADMIT'), (103, 'PLAN_DISCHARGE'), (104, 'CASHIER_DISCHARGE'), (105, 'FINISH')])),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EncounterCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4, unique=True)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Icd10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=1000)),
                ('term_detail', models.CharField(blank=True, max_length=1000)),
                ('term_sub_detail', models.CharField(blank=True, max_length=1000)),
                ('has_sublevel', models.BooleanField(default=False)),
                ('is_principal_opd', models.BooleanField(default=False)),
                ('is_principal_ipd', models.BooleanField(default=False)),
                ('start_age', models.IntegerField(default=-1)),
                ('end_age', models.IntegerField(default=-1)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'รหัส ICD10',
            },
        ),
        migrations.CreateModel(
            name='Icd10MedicalTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=255)),
                ('seq', models.IntegerField(default=255)),
            ],
            options={
                'verbose_name': 'ชื่อเรียก ICD10 ที่แพทย์เข้าใจ',
            },
        ),
        migrations.CreateModel(
            name='Icd10Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง')),
            ],
            options={
                'verbose_name': 'รุ่นของ ICD10',
            },
        ),
        migrations.CreateModel(
            name='Icd9cm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('term', models.CharField(max_length=1000)),
                ('term_detail', models.CharField(blank=True, max_length=1000)),
                ('term_sub_detail', models.TextField(blank=True)),
                ('has_sublevel', models.BooleanField(default=False)),
                ('is_principal_opd', models.BooleanField(default=False)),
                ('is_principal_ipd', models.BooleanField(default=False)),
                ('start_age', models.IntegerField(default=-1)),
                ('end_age', models.IntegerField(default=-1)),
                ('male', models.BooleanField(default=False)),
                ('female', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'รหัส ICD9CM',
            },
        ),
        migrations.CreateModel(
            name='Icd9cmMedicalTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, max_length=255)),
                ('seq', models.IntegerField(default=255)),
            ],
            options={
                'verbose_name': 'ชื่อเรียก ICD9CM ที่แพทย์เข้าใจ',
            },
        ),
        migrations.CreateModel(
            name='Icd9cmVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'รุ่นของ ICD9CM',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('active', models.BooleanField(default=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('checkout_cause', his.framework.models.fields.EnumField(blank=True, enum=[(1, 'BY_APPROVAL'), (2, 'ADMIT'), (3, 'ER'), (4, 'REFER_OUT'), (5, 'REJECT'), (6, 'DEAD')], null=True, verbose_name='สาเหตุการสิ้นสุดการรักษา')),
            ],
            options={
                'verbose_name': 'เวชระเบียนทางการแพทย์ของผู้ป่วย',
            },
        ),
        migrations.CreateModel(
            name='MiscellaneousOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='a quantity of product to be charged')),
                ('perform_datetime', models.DateTimeField(help_text='a date and time when order was performed.')),
                ('active', models.BooleanField(default=True, help_text='is the order active?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['display_seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('type', his.framework.models.fields.EnumField(default=1, enum=[(1, 'NORMAL'), (2, 'TEMP')])),
                ('hn', models.CharField(blank=True, max_length=10, unique=True, verbose_name='หมายเลข HN')),
                ('first_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อ')),
                ('middle_name', models.CharField(blank=True, max_length=80, verbose_name='ชื่อกลาง')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='นามสกุล')),
                ('first_name_th', models.CharField(blank=True, max_length=200, verbose_name='ชื่อภาษาไทย')),
                ('middle_name_th', models.CharField(blank=True, max_length=80, verbose_name='ชื่อกลางภาษาไทย')),
                ('last_name_th', models.CharField(blank=True, max_length=200, verbose_name='นามสกุลภาษาไทย')),
                ('first_name_en', models.CharField(blank=True, max_length=80, validators=[his.framework.utils.validate_english], verbose_name='ชื่อภาษาอังกฤษ')),
                ('middle_name_en', models.CharField(blank=True, max_length=80, validators=[his.framework.utils.validate_english], verbose_name='ชื่อกลางภาษาอังกฤษ')),
                ('last_name_en', models.CharField(blank=True, max_length=80, validators=[his.framework.utils.validate_english], verbose_name='นามสกุลภาษาอังกฤษ')),
                ('sequence', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Undetermined'), ('PM', 'Male(Not Approved)'), ('PF', 'Female(Not Appoved)')], default='M', max_length=2, verbose_name='เพศ')),
                ('marriage', models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('E', 'Engaged'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=1, verbose_name='สถานภาพ')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('birthdate_year_only', models.BooleanField(default=False, verbose_name='ทราบวันเกิดแค่ปี')),
                ('deathdate', models.DateTimeField(blank=True, null=True, verbose_name='วันและเวลาตาย')),
                ('student_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='รหัสนักศึกษา')),
                ('employee_no', models.CharField(blank=True, max_length=15, null=True, verbose_name='รหัสพนักงาน')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='วันที่')),
                ('patient_count', models.IntegerField(verbose_name='จำนวนผู้ป่วยในวัน')),
            ],
        ),
        migrations.CreateModel(
            name='PatientCoverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('service_type', models.CharField(choices=[('O', 'ผู้ป่วยนอก'), ('I', 'ผู้ป่วยใน')], help_text='ประเภทบริการ', max_length=2, verbose_name='ประเภทบริการ')),
                ('claim_code', models.CharField(blank=True, max_length=50)),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มต้นคุ้มครอง')),
                ('stop_date', models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการคุ้มครอง')),
                ('active', models.BooleanField(default=True, help_text='ใช้สิทธิ์ หรือระงับสิทธิ์')),
                ('referer', models.CharField(blank=True, help_text='โรงพยาบาลต้นสังกัดกรณีผู้ป่วย Refer-in', max_length=255, null=True)),
                ('refer_date', models.DateField(blank=True, null=True)),
                ('refer_no', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(default=99, verbose_name='ลำดับการเลือกใช้สิทธิ์')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('payer_id', models.CharField(max_length=10, verbose_name='รหัส Payer')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ Payer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PayerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('payer_group_id', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อกลุ่ม Payer')),
            ],
            options={
                'verbose_name': 'กลุ่ม Payer',
                'verbose_name_plural': 'กลุ่ม Payer',
            },
        ),
        migrations.CreateModel(
            name='Prename',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='คำนำหน้าชื่อ', max_length=20)),
                ('language', models.CharField(choices=[('TH', 'Thai'), ('EN', 'English')], default='TH', max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'ไม่ระบุ')], default='M', max_length=1, verbose_name='เพศ')),
            ],
            options={
                'ordering': ['display_seq'],
            },
        ),
        migrations.CreateModel(
            name='PrintLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันเวลาที่พิมพ์')),
                ('report_name', models.CharField(max_length=255, verbose_name='เอกสารที่สั่งพิมพ์')),
                ('hn', models.CharField(blank=True, default='', max_length=10, verbose_name='หมายเลข HN')),
            ],
            options={
                'verbose_name': 'ประวัติการพิมพ์เอกสาร',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('unit', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('observation_type', models.CharField(max_length=20, null=True, verbose_name='ประเภทการให้บริการ')),
            ],
            options={
                'verbose_name': 'ประเภทค่าใช้จ่าย',
            },
        ),
        migrations.CreateModel(
            name='ProgressionCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('progression_note', models.TextField(blank=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'สิทธิโครงการ',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name_en', models.CharField(max_length=40)),
                ('zone', models.CharField(max_length=30)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Referer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสโรงพยาบาลต้นสังกัด')),
            ],
            options={
                'verbose_name': 'โรงพยาบาลต้นสังกัดกรณีผู้ป่วย Refer-in',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['display_seq'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScannedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='วันที่สแกนเอกสาร')),
                ('document_code', models.CharField(blank=True, max_length=50, verbose_name='รหัสเอกสาร')),
                ('page', models.IntegerField(default=1, verbose_name='เลขหน้าเอกสาร')),
                ('document_image', models.ImageField(upload_to='patient/scanned_document/', verbose_name='ภาพสแกนเอกสาร')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'ภาพสแกนเอกสารผู้ป่วย',
            },
        ),
        migrations.CreateModel(
            name='SpecialEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'สาขาเฉพาะทางของแพทย์',
                'verbose_name_plural': 'สาขาเฉพาะทางของแพทย์',
            },
        ),
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('chief_complaint', models.CharField(max_length=255)),
                ('arrive_status', models.CharField(choices=[('WLK', 'เดิน'), ('WCH', 'รถนั่ง'), ('CRT', 'รถนอน')], default='WLK', max_length=3, verbose_name='สถานะการมา')),
                ('case', models.CharField(choices=[('LAW', 'เคสคดีความ'), ('ACT', 'อุบัติเหตุหมู่'), ('EMR', 'อุบัติเหตุฉุกเฉิน'), ('GEN', 'ทั่วไป')], default='GEN', max_length=3)),
                ('patient_type', models.CharField(choices=[('WLK', 'Walk-in'), ('APP', 'นัดหมาย'), ('REF', 'Refer-in'), ('CON', 'Consult'), ('TRF', 'ถูกส่งมาจากหน่วยงานอื่น')], default='WLK', max_length=3, verbose_name='ประเภทผู้ป่วย')),
                ('referer', models.CharField(blank=True, max_length=255)),
                ('triage_level', models.CharField(choices=[('1', 'Life Threatening'), ('2', 'Emergency'), ('3', 'Urgency'), ('4', 'Semi-Urgency'), ('5', 'ทั่วไป')], default='5', max_length=3, verbose_name='ระดับการคัดกรอง')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Division')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='an abbreviation of the unit of measure', max_length=10, unique=True)),
                ('name', models.CharField(help_text='a name of the unit of measure', max_length=255)),
                ('name_en', models.CharField(blank=True, help_text='a name of the unit of measure', max_length=255)),
                ('dosage_size', models.PositiveIntegerField(default=0, help_text='หน่วยย่อยสุดต่อหน่วยกิน เช่น 5 ml/ช้อนโต๊ะ')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('base_unit', models.ForeignKey(blank=True, help_text='หน่วยย่อยสุด เช่น ml หรือ เม็ด', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit')),
            ],
            options={
                'verbose_name': 'unit of measure for product',
                'verbose_name_plural': 'units of measure for product',
            },
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
            ],
            bases=('core.product',),
        ),
    ]
