# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='specialequipment',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
        migrations.AddField(
            model_name='specialequipment',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentType', verbose_name='ประเภทเอกสาร'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='encounter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='province',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_country', to='core.Country'),
        ),
        migrations.AddField(
            model_name='project',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='progressioncycle',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='progressioncycle',
            name='emr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progression_cycles', to='core.MedicalRecord'),
        ),
        migrations.AddField(
            model_name='product',
            name='p_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProductType'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division', verbose_name='แผนกที่สั่งพิมพ์'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ผู้สั่งพิมพ์'),
        ),
        migrations.AddField(
            model_name='payergroup',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='payer',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='payer',
            name='payer_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PayerGroup', verbose_name='กลุ่ม Payer'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coverage'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Payer'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='โครงการ'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='service_point',
            field=models.ManyToManyField(blank=True, help_text='จุดบริการ', to='core.Division', verbose_name='หน่วยงาน'),
        ),
        migrations.AddField(
            model_name='patient',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='patient',
            name='location',
            field=models.ForeignKey(blank=True, help_text='สถานที่ล่าสุดที่ให้บริการผู้ป่วย', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Location'),
        ),
        migrations.AddField(
            model_name='patient',
            name='natural_mother',
            field=models.ForeignKey(blank=True, help_text='มารดาผู้ให้กำเนิด กรณีเป็นเด็กเกิดใหม่ที่โรงพยาบาล', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre_name_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อภาษาอังกฤษ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='pre_name_th',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อภาษาไทย'),
        ),
        migrations.AddField(
            model_name='miscellaneousorder',
            name='encounter',
            field=models.ForeignKey(help_text='an encounter of the patient whose to be charged', on_delete=django.db.models.deletion.CASCADE, to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='miscellaneousorder',
            name='performing_division',
            field=models.ForeignKey(help_text='a division performed the order', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AddField(
            model_name='miscellaneousorder',
            name='requesting_division',
            field=models.ForeignKey(help_text='a division requested the order', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor', verbose_name='แพทย์ผู้ตรวจ'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emrs', to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='icd9cmmedicalterm',
            name='icd9cm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Icd9cm'),
        ),
        migrations.AddField(
            model_name='icd9cm',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Icd9cmVersion'),
        ),
        migrations.AddField(
            model_name='icd10medicalterm',
            name='icd10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Icd10'),
        ),
        migrations.AddField(
            model_name='icd10',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Icd10Version'),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Coverage', verbose_name='สิทธิผู้ป่วย'),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payer'),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Project', verbose_name='โครงการ'),
        ),
        migrations.AddField(
            model_name='encounteractionlog',
            name='statable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='encounteractionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encounter',
            name='discharge_status',
            field=models.ForeignKey(blank=True, help_text='Discharge Status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ClinicalTerm'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Doctor'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='predischarge_condition',
            field=models.ForeignKey(blank=True, help_text='สภาพผู้ป่วยก่อนจำหน่าย', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ClinicalTerm'),
        ),
        migrations.AddField(
            model_name='encounter',
            name='triage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Triage'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='division',
            field=models.ManyToManyField(to='core.Division'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='emr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.MedicalRecord'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Encounter'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doctor', verbose_name='แพทย์ผู้สั่ง'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_div',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division', verbose_name='แผนกที่สั่ง'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_perform_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้ปฏิบัติคำสั่ง'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_perform_div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division', verbose_name='แผนกที่ทำ'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_receive_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับคำสั่งแทน'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='progression_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ProgressionCycle'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='specific_type',
            field=models.ForeignKey(editable=False, help_text='specific type of order', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='pre_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Prename'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Specialty'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='division',
            name='billing_div',
            field=models.ForeignKey(blank=True, help_text='การเงินที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='drug_div',
            field=models.ForeignKey(blank=True, help_text='ห้องยาที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='supply_div',
            field=models.ForeignKey(blank=True, help_text='ห้องเวชภัณฑ์ที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AddField(
            model_name='district',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='district_province', to='core.Province'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='coverage',
            name='payers',
            field=models.ManyToManyField(blank=True, help_text='Payer ที่สามารถใช้งานกับสิทธิ์นี้ได้(ไม่ระบุ = สามารถใช้ได้ทุก Payer)', to='core.Payer', verbose_name='Payer List'),
        ),
        migrations.AddField(
            model_name='city',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_district', to='core.District'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_city', to='core.City'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='core.Country'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_district', to='core.District'),
        ),
        migrations.AddField(
            model_name='address',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_province', to='core.Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address_type', to='core.HomeType'),
        ),
        migrations.AddField(
            model_name='miscellaneousorder',
            name='product',
            field=models.ForeignKey(help_text='a product to be charged', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Miscellaneous'),
        ),
    ]
