# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170807_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('value', models.IntegerField(help_text='จำนวนชั่วโมงที่ทำความสะอาด')),
            ],
            options={
                'verbose_name': 'ตัวเลือกประเภทเวลาในการทำความสะอาด หลังจากผู้ป่วยออกจากห้อง',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='cleaning',
            field=models.ForeignKey(blank=True, help_text='ประเภทเวลาในการทำความสะอาด', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.CleaningChoice'),
        ),
    ]
