# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 11:44
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170808_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcoverage',
            name='coverage_type',
            field=his.framework.models.fields.EnumField(default=10, enum=[(1, 'EMERGENCY'), (2, 'ACCIDENT'), (3, 'REFER'), (4, 'PROJECT'), (5, 'HANDICAP'), (10, 'UNDEFINED')], verbose_name='ประเภทสิทธิ์'),
        ),
        migrations.AlterField(
            model_name='coverage',
            name='type',
            field=his.framework.models.fields.EnumField(default=1, enum=[(1, 'COVERAGE'), (2, 'DISCOUNT_POLICY'), (3, 'DISCOUNT_CARD')], verbose_name='ประเภทสิทธิ์'),
        ),
    ]
