# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 18:07
from __future__ import unicode_literals

from django.db import migrations, models
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170809_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', his.framework.models.fields.EnumField(enum=[(1, 'ENCOUNTER_OPD'), (2, 'ENCOUNTER_IPD'), (3, 'ENCOUNTER_SS'), (4, 'HN')])),
                ('prefix', models.CharField(max_length=8)),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='runningnumber',
            unique_together=set([('type', 'prefix')]),
        ),
    ]
