# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 10:40
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170809_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountercoverage',
            name='coverage_type',
            field=his.framework.models.fields.EnumField(default=10, enum=[(1, 'EMERGENCY'), (2, 'ACCIDENT'), (3, 'REFER'), (4, 'PROJECT'), (5, 'HANDICAP'), (10, 'UNDEFINED')], verbose_name='ประเภทสิทธิ์'),
        ),
    ]
