# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_encountercoverage_coverage_type'),
        ('core', '0006_auto_20170815_0953'),
    ]

    operations = [
    ]
