# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 16:36
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20170815_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='type',
            field=his.framework.models.fields.EnumField(default=1, enum=[(1, 'GENERAL'), (2, 'BILLING'), (3, 'DRUG'), (4, 'SUPPLY'), (5, 'TREATMENT'), (6, 'SPECIMEN_COLLECTOR'), (7, 'CLINIC'), (8, 'PREMIUM_CLINIC'), (9, 'WARD')], verbose_name='ประเภทหน่วยงาน'),
        ),
    ]
