# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-21 10:47
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20170817_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounteractionlog',
            name='action',
            field=his.framework.models.fields.EnumField(enum=[(1, 'OPD_NEW'), (2, 'OPD_TRIAGE'), (3, 'OPD_ARRIVE'), (4, 'OPD_SCREEN'), (5, 'OPD_QUEUE_EXAM'), (6, 'OPD_CHECK_IN'), (7, 'OPD_CHECK_OUT'), (8, 'OPD_DISCHARGE'), (9, 'OPD_PAID'), (10, 'OPD_DISPENSE'), (11, 'OPD_SEND_LAB'), (12, 'OPD_SEND_TREATMENT'), (13, 'OPD_EDIT'), (14, 'OPD_REFILL'), (15, 'OPD_FINISH_LAB'), (16, 'OPD_FINISH_TREATMENT'), (101, 'ADMISSION_ADMIT'), (102, 'ADMIT'), (103, 'PLAN_DISCHARGE'), (104, 'CASHIER_DISCHARGE'), (105, 'FINISH')]),
        ),
    ]
