# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170821_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalterm',
            name='type',
            field=models.CharField(choices=[('A', 'อาการเบื้องต้น'), ('B', 'จุดสังเกต'), ('C', 'แพ้ยา'), ('D', 'โรคประจำตัว'), ('E', 'เหตุผลเปลี่ยนชื่อ'), ('F', 'ความสัมพันธ์'), ('G', 'เหตุผลยกเลิกนามแฝง'), ('H', 'สภาพผู้ป่วยก่อนจำหน่าย'), ('I', 'Discharge Status'), ('FA', 'Functional Assessment')], max_length=3),
        ),
    ]
