# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:13
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20170821_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='billing_div',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, help_text='การเงินที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='drug_div',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, help_text='ห้องยาที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='supply_div',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, help_text='ห้องเวชภัณฑ์ที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='natural_mother',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, help_text='มารดาผู้ให้กำเนิด กรณีเป็นเด็กเกิดใหม่ที่โรงพยาบาล', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Patient'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='base_unit',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, help_text='หน่วยย่อยสุด เช่น ml หรือ เม็ด', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Unit'),
        ),
    ]
