# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 18:36
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170823_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='checkout_cause',
            field=his.framework.models.fields.EnumField(blank=True, enum=[(1, 'BY_APPROVAL'), (2, 'ADMIT'), (3, 'ER'), (4, 'REFER_OUT'), (5, 'REJECT'), (6, 'DEAD'), (7, 'DISAPPEAR')], null=True, verbose_name='สาเหตุการสิ้นสุดการรักษา'),
        ),
    ]
