# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-31 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def load_clinical_term_set(apps, schema_editor):
    ClinicalTerm = apps.get_model('core', 'ClinicalTerm')
    if ClinicalTerm.objects.all().count() > 0:
        ClinicalTermSet = apps.get_model('core', 'ClinicalTermSet')
        ClinicalTermSet.objects.get_or_create(id=1, defaults=dict(code='A',
                                                                  name='อาการเบื้องต้น',
                                                                  active=True))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20170828_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalTermSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='clinicalterm',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='default สำหรับตัวเลือกในหน้าจอ'),
        ),
        migrations.AddField(
            model_name='clinicalterm',
            name='seq',
            field=models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='clinicalterm',
            name='type',
        ),
        migrations.RunPython(load_clinical_term_set, reverse_code=lambda a, b: True),
        migrations.AddField(
            model_name='clinicalterm',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ClinicalTermSet', verbose_name='ประเภท Clinical Term'),
            preserve_default=False,
        ),
    ]
