# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 18:05
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_merge_20170824_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='type',
            field=his.framework.models.fields.EnumField(default=1, enum=[(1, 'TYPE_NORMAL'), (2, 'TYPE_SYSTEM')], verbose_name='ประเภทของแพทย์'),
        ),
    ]
