# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_doctor_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='alias',
            field=models.CharField(blank=True, help_text='a meaningful abbreviation', max_length=10),
        ),
    ]
