# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_doctor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionStopWorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('start_date', models.DateField(help_text='วันที่เริ่มต้นหยุดให้บริการ', verbose_name='วันเริ่มต้น')),
                ('end_date', models.DateField(blank=True, help_text='วันที่สิ้นสุดการหยุดให้บริการ', null=True, verbose_name='วันสิ้นสุด')),
                ('start_time', models.TimeField(help_text='เวลาที่เริ่มต้นการหยุดให้บริการ', verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.TimeField(help_text='เวลาที่สิ้นสุดการหยุดให้บริการ', verbose_name='เวลาสิ้นสุด')),
                ('active', models.BooleanField(default=True, help_text='True = active, False = not active', verbose_name='active flag')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division', verbose_name='หน่วยงาน')),
                ('edit_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name_plural': 'ตารางงดเปิดให้บริการของหน่วยงาน',
                'verbose_name': 'ตารางงดเปิดให้บริการของหน่วยงาน',
            },
        ),
        migrations.CreateModel(
            name='DivisionWorkSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='วันที่เริ่มต้น', verbose_name='วันเริ่มต้น')),
                ('end_date', models.DateField(blank=True, help_text='วันที่สิ้นสุดการ', null=True, verbose_name='วันสิ้นสุด')),
                ('start_time', models.TimeField(help_text='เวลาที่เริ่มต้น', verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.TimeField(help_text='เวลาที่สิ้นสุด', verbose_name='เวลาสิ้นสุด')),
                ('work_on_monday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันจันทร์')),
                ('work_on_tuesday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันอังคาร')),
                ('work_on_wednesday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันพุธ')),
                ('work_on_thursday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันพฤหัส')),
                ('work_on_friday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันศุกร์')),
                ('work_on_saturday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันเสาร์')),
                ('work_on_sunday', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการวันอาทิตย์')),
                ('work_on_week_1', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 1')),
                ('work_on_week_2', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 2')),
                ('work_on_week_3', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 3')),
                ('work_on_week_4', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 4')),
                ('work_on_week_5', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 5')),
                ('work_on_week_6', models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการอาทิตย์ที่ 6')),
                ('active', models.BooleanField(default=True, help_text='True = active, False = not active', verbose_name='active flag')),
                ('division', models.ForeignKey(help_text='หน่วยงาน', on_delete=django.db.models.deletion.CASCADE, to='core.Division', verbose_name='หน่วยงาน')),
            ],
            options={
                'verbose_name_plural': 'ตารางการเปิดให้บริการของหน่วยงาน',
                'verbose_name': 'ตารางการเปิดให้บริการของหน่วยงาน',
            },
        ),
    ]
