# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_unit_alias'),
        ('core', '0014_divisionstopworkschedule_divisionworkschedule'),
    ]

    operations = [
    ]
