# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_merge_20170830_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='clinic_type',
            field=models.CharField(choices=[('RGL', 'Regular (ปกติ)'), ('SPC', 'Special (นอกเวลา)'), ('PRM', 'Premium')], default='RGL', max_length=3),
        ),
    ]
