# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-04 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20170831_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousorder',
            name='encounter',
            field=models.ForeignKey(help_text='an encounter of the patient whose to be charged', on_delete=django.db.models.deletion.CASCADE, related_name='miscellaneous_orders', to='core.Encounter'),
        ),
    ]
