# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-05 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20170831_1206'),
        ('core', '0017_auto_20170904_1143'),
    ]

    operations = [
    ]
