# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-07 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20170905_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='type',
            field=models.CharField(choices=[('OPD', 'OPD'), ('IPD', 'IPD'), ('SS', 'Short Stay'), ('ER', 'ER'), ('OTH', 'OTH')], max_length=4),
        ),
    ]
