# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:19
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models

import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20170907_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, help_text='ประเภทของเอกสาร')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coverage')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentType')),
            ],
        ),
    ]
