# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_coveragedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicalterm',
            name='has_description',
            field=models.BooleanField(default=False, verbose_name='ตัวเลือกนี้มีรายละเอียดเพิ่มเติมหรือไม่'),
        ),
    ]
