# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def clearTriageData(apps, schema_editor):
    """
    Reset triage data to point to ClinicalTerm with id=1 as default value.
    Preventing error on model migration
    """
    # We can't import the Triage model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Triage = apps.get_model('core', 'triage')
    for triage in Triage.objects.all():
        triage.arrive_status = '1'
        triage.case = '1'
        triage.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_clinicalterm_has_description'),
    ]

    operations = [
        migrations.RunPython(clearTriageData),
        migrations.AlterField(
            model_name='triage',
            name='arrive_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_arrive_status', to='core.ClinicalTerm', verbose_name='สถานะการมา'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_case', to='core.ClinicalTerm', verbose_name='ประเภท case ผู้ป่วย'),
        ),
        migrations.AlterField(
            model_name='triage',
            name='referer',
            field=models.CharField(blank=True, max_length=255, verbose_name='ผู้นำส่ง'),
        ),
    ]
