# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_planitem_planitemactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='actual_orders',
            field=models.ManyToManyField(help_text='PlanItem ที่ ผูกกับ DoctorOrder ที่ถูก Clone', related_name='created_from_plan_items', to='core.DoctorOrder', verbose_name='รายการที่ถูกสร้างแล้ว'),
        ),
        migrations.AlterField(
            model_name='planitem',
            name='plan_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item', to='core.DoctorOrder', verbose_name='รายการต้นแบบที่จะถูกสร้างเมื่อถึงเวลา'),
        ),
    ]
