# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20170913_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('display_seq',)},
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='division',
            field=models.ManyToManyField(blank=True, help_text='ระบุ Division ที่ใช้เอกสารชนิดนี้ (เว้นว่าง = ใช้ได้ทุก Division)', to='core.Division'),
        ),
    ]
