# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20170913_1617'),
        ('core', '0026_auto_20170914_1723'),
    ]

    operations = [
    ]
