# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 11:58
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_merge_20170914_1737'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encountercoverage',
            old_name='coverage_type',
            new_name='assure_type',
        ),
        migrations.RemoveField(
            model_name='patientcoverage',
            name='coverage_type',
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='assure_type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=10, verbose_name='ประเภทการรับรองสิทธิ์'),
        ),
        migrations.AlterUniqueTogether(
            name='encountercoverage',
            unique_together=set([('encounter', 'coverage')]),
        ),
    ]
