# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0028_auto_20170915_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('type', models.CharField(choices=[('OP', 'Principal Diagnosis'), ('OS', 'Secondary Diagnosis'), ('IP', 'Provisional Diagnosis'), ('IF', 'Final(Primary) Diagnosis'), ('IS', 'Secondary Diagnosis')], max_length=2, verbose_name='ชนิดของ Diagnosis')),
                ('medical_description', models.TextField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='สาเหตุเพิ่มเติม')),
                ('edit_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('emr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.MedicalRecord', verbose_name='Electronic Medical Record')),
                ('icd10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Icd10')),
                ('icd10_med_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Icd10MedicalTerm')),
            ],
            options={
                'verbose_name': 'ผลวิเคราะห์อาการป่วย',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ Template โรค')),
                ('division', models.ManyToManyField(related_name='_diagnosistemplate_division_+', to='core.Division')),
            ],
            options={
                'verbose_name': 'ชื่อ Template ของ Diagnosis',
            },
        ),
        migrations.CreateModel(
            name='DiagnosisTemplateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OP', 'Principal Diagnosis'), ('OS', 'Secondary Diagnosis'), ('IP', 'Provisional Diagnosis'), ('IF', 'Final(Primary) Diagnosis'), ('IS', 'Secondary Diagnosis')], max_length=2, verbose_name='ชนิดของ Diagnosis')),
                ('diag_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.DiagnosisTemplate')),
                ('icd10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Icd10')),
                ('icd10_med_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Icd10MedicalTerm')),
            ],
            options={
                'verbose_name': 'รายละเอียด Template ของ Diagnosis',
            },
        ),
    ]
