# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_diagnosis_diagnosistemplate_diagnosistemplatedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='emr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_diagnosis', to='core.MedicalRecord', verbose_name='Electronic Medical Record'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd10',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_diagnosis', to='core.Icd10'),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='icd10_med_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_diagnosis', to='core.Icd10MedicalTerm'),
        ),
        migrations.AlterField(
            model_name='diagnosistemplate',
            name='division',
            field=models.ManyToManyField(related_name='core_diag_template', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='diagnosistemplatedetail',
            name='diag_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_diag_template_detail', to='core.DiagnosisTemplate'),
        ),
        migrations.AlterField(
            model_name='diagnosistemplatedetail',
            name='icd10',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_diag_template_detail', to='core.Icd10'),
        ),
        migrations.AlterField(
            model_name='diagnosistemplatedetail',
            name='icd10_med_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_diag_template_detail', to='core.Icd10MedicalTerm'),
        ),
    ]
