# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20170918_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='type',
            new_name='old_type',
        ),
    ]
