# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:23
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20170919_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1, verbose_name='ชนิดของ Diagnosis'),
            preserve_default=False,
        ),
    ]
