# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:23
from __future__ import unicode_literals

from django.db import migrations


def migrate_diagnosis_type(apps, schema_editor):
    """Migrate diagnosis type from OPD char field to enum field"""
    Diagnosis = apps.get_model('core', 'Diagnosis')
    for diagnosis in Diagnosis.objects.all():
        if diagnosis.old_type == 'OP' or diagnosis.old_type == 'IF':
            diagnosis.type = 1  # Diagnosis.TYPE.PRIMARY
        elif diagnosis.old_type == 'OS':
            diagnosis.type = 2  # Diagnosis.TYPE.SECONARY
        elif diagnosis.old_type == 'IP':
            diagnosis.type = 3  # Diagnosis.TYPE.PROVISIONAL_PRIMARY
        elif diagnosis.old_type == 'IS':
            diagnosis.type = 4  # Diagnosis.TYPE.SECONDARY_COMORBID
        else:
            diagnosis.type = 2  # Diagnosis.TYPE.SECONARY
        diagnosis.save()
    DiagnosisDetail = apps.get_model('core', 'DiagnosisTemplateDetail')
    for diagnosis in DiagnosisDetail.objects.all():
        if diagnosis.type == 'OP' or diagnosis.type == 'IF':
            diagnosis.type = 1  # Diagnosis.TYPE.PRIMARY
        elif diagnosis.type == 'OS':
            diagnosis.type = 2  # Diagnosis.TYPE.SECONARY
        elif diagnosis.type == 'IP':
            diagnosis.type = 3  # Diagnosis.TYPE.PROVISIONAL_PRIMARY
        elif diagnosis.type == 'IS':
            diagnosis.type = 4  # Diagnosis.TYPE.SECONDARY_COMORBID
        else:
            diagnosis.type = 2  # Diagnosis.TYPE.SECONARY
        diagnosis.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_diagnosis_type'),
    ]

    operations = [
        migrations.RunPython(migrate_diagnosis_type),
    ]
