# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 12:26
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20170919_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='old_type',
        ),
        migrations.AlterField(
            model_name='diagnosistemplatedetail',
            name='type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ชนิดของ Diagnosis'),
        ),
    ]
