# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 17:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0034_auto_20170919_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1, verbose_name='ชนิดของ Procedure')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('medical_description', models.TextField(blank=True, default='')),
                ('edit_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('emr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure', to='core.MedicalRecord', verbose_name='Electronic Medical Record')),
                ('icd9cm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure', to='core.Icd9cm')),
                ('icd9cm_med_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure', to='core.Icd9cmMedicalTerm')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure', to='core.DoctorOrder', verbose_name='Doctor Order')),
            ],
            options={
                'verbose_name': 'การทำหัตถการ',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อ Template หัตถการ')),
                ('division', models.ManyToManyField(related_name='core_procedure_template', to='core.Division')),
            ],
            options={
                'verbose_name': 'ชื่อ Template ของ Procedure',
            },
        ),
        migrations.CreateModel(
            name='ProcedureTemplateDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ชนิดของ Procedure')),
                ('icd9cm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure_template_detail', to='core.Icd9cm')),
                ('icd9cm_med_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure_template_detail', to='core.Icd9cmMedicalTerm')),
                ('procedure_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure_template_detail', to='core.ProcedureTemplate')),
            ],
            options={
                'verbose_name': 'รายละเอียด Template ของ Procedure',
            },
        ),
    ]
