# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20170919_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitemactionlog',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
