# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 11:29
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_procedure_proceduretemplate_proceduretemplatedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ชนิดของ Procedure'),
        ),
    ]
