# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_planitemactionlog_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='unit',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='base_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='dosage_size',
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='from_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Unit'),
        ),
        migrations.AddField(
            model_name='unitconversion',
            name='to_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unitconversion',
            unique_together=set([('from_unit', 'to_unit')]),
        ),
    ]
