# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20170922_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('code',), 'verbose_name': 'unit of measure for product', 'verbose_name_plural': 'units of measure for product'},
        ),
    ]
