# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_auto_20170925_0940'),
        ('core', '0036_auto_20170920_1129'),
    ]

    operations = [
    ]
