# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-28 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20170927_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='billing_div',
            field=models.ForeignKey(blank=True, help_text='การเงินที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='drug_div',
            field=models.ForeignKey(blank=True, help_text='ห้องยาที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
        migrations.AlterField(
            model_name='division',
            name='supply_div',
            field=models.ForeignKey(blank=True, help_text='ห้องเวชภัณฑ์ที่ผูกกับหน่วยตรวจ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division'),
        ),
    ]
