# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20170928_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_1',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 1'),
        ),
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_2',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 2'),
        ),
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_3',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 3'),
        ),
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_4',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 4'),
        ),
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_5',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 5'),
        ),
        migrations.AlterField(
            model_name='divisionworkschedule',
            name='work_on_week_6',
            field=models.BooleanField(default=True, help_text='True = เปิดให้บริการ, False = ไม่เปิดให้บริการ', verbose_name='เปิดให้บริการสัปดาห์ที่ 6'),
        ),
    ]
