# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170928_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sequence',
            field=models.CharField(default='', max_length=80),
        ),
    ]
