# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 16:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20170929_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='runningnumber',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 29, 16, 41, 6, 711336)),
            preserve_default=False,
        ),
    ]
