# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20171002_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='belief',
            field=models.TextField(blank=True, null=True, verbose_name='ความเชื่อ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ClinicalTerm', verbose_name='เชื้อชาติ'),
        ),
    ]
