# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20171003_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialequipment',
            name='division',
        ),
        migrations.RemoveField(
            model_name='specialequipment',
            name='product',
        ),
        migrations.DeleteModel(
            name='SpecialEquipment',
        ),
        migrations.CreateModel(
            name='SpecialEquipment',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=models.deletion.CASCADE, to='core.Division')),
            ],
            bases=('core.product',),
        ),
    ]
