# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20171006_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, editable=False)),
                ('counting_datetime', models.DateTimeField(editable=False, null=True)),
                ('bin_location', models.CharField(max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Storage'),
        ),
        migrations.AddField(
            model_name='division',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Storage', verbose_name='คลังที่ผูกกับหน่วยงานนี้'),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set([('product', 'storage')]),
        ),
    ]
