# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20171010_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousorder',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
