# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_division_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncounterNumberIPD',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.encounter',),
        ),
        migrations.CreateModel(
            name='EncounterNumberOPD',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.encounter',),
        ),
        migrations.CreateModel(
            name='EncounterNumberSSS',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.encounter',),
        ),
    ]
