# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20171020_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='sap_code',
            field=models.CharField(default='', max_length=10, blank=True),
            preserve_default=False,
        ),
    ]
