# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20171020_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(null=True)),
                ('check_out_time', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Division'),
        ),
        migrations.AddField(
            model_name='zonelog',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_log', to='core.Division'),
        ),
        migrations.AddField(
            model_name='zonelog',
            name='encounter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_log', to='core.Encounter'),
        ),
    ]
