# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20171020_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='allow_cancel_receipt_when_performed',
            field=models.BooleanField(default=True, help_text='อนุญาตให้ยกเลิกใบเสร็จ ถ้า perform รายการแล้ว'),
        ),
    ]
