# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-01 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_storage_sap_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='division',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
