# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_division_short_name'),
        ('core', '0054_auto_20171101_1744'),
    ]

    operations = [
    ]
