# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_merge_20171101_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Division'),
        ),
    ]
