# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_producttype_allow_cancel_receipt_when_performed'),
        ('core', '0057_auto_20171101_1853'),
    ]

    operations = [
    ]
