# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_20171102_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenWelfare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_id', models.IntegerField(unique=True)),
                ('citizen_no', models.CharField(max_length=100)),
                ('employee_no', models.CharField(blank=True, max_length=100)),
                ('employee_type', models.CharField(blank=True, max_length=100)),
                ('year_of_work', models.CharField(blank=True, max_length=100)),
                ('record_date', models.DateTimeField()),
                ('record_by', models.CharField(blank=True, max_length=100)),
                ('status', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('update_need', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WelfareCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='citizenwelfare',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.WelfareCategory'),
        ),
        migrations.AddField(
            model_name='citizenwelfare',
            name='coverage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Coverage'),
        ),
    ]
