# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_merge_20171102_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zonelog',
            old_name='division',
            new_name='zone',
        ),
    ]
