# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20171106_1203'),
        ('core', '0059_auto_20171106_1150'),
    ]

    operations = [
    ]
