# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 12:26
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_merge_20171106_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousorder',
            name='eligibility_type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1),
        ),
    ]
