# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_miscellaneousorder_eligibility_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.Storage', verbose_name='คลังที่ผูกกับหน่วยงานนี้'),
        ),
    ]
