# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20171109_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonelog',
            name='create_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
