# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20171109_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountercoverage',
            name='refer_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='refer_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='referer',
            field=models.CharField(blank=True, help_text='โรงพยาบาลต้นสังกัดกรณีผู้ป่วย Refer-in', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='วันที่เริ่มต้นคุ้มครอง'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='stop_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่สิ้นสุดการคุ้มครอง'),
        ),
        migrations.AlterField(
            model_name='encountercoverage',
            name='assure_type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=10, verbose_name='ประเภทการรับรองสิทธิ์'),
        ),
        migrations.AlterField(
            model_name='encountercoverage',
            name='coverage',
            field=models.ForeignKey(default=30, on_delete=django.db.models.deletion.CASCADE, to='core.Coverage', verbose_name='สิทธิผู้ป่วย'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encountercoverage',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payer', verbose_name='ผู้จ่ายเงิน'),
        ),
        migrations.AlterField(
            model_name='patientcoverage',
            name='coverage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coverage', verbose_name='สิทธิผู้ป่วย'),
        ),
        migrations.AlterField(
            model_name='patientcoverage',
            name='payer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Payer', verbose_name='ผู้จ่ายเงิน'),
        ),
    ]
