# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20171110_1232'),
        ('core', '0064_auto_20171110_1258'),
    ]

    operations = [
    ]
