# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20171110_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='service_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
