# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_merge_20171110_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='payer',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Province', verbose_name='จังหวัด'),
        ),
        migrations.AddField(
            model_name='payer',
            name='short_name',
            field=models.CharField(default='', max_length=255, verbose_name='ชื่อ Payer แบบสั้น'),
        ),
    ]
