# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_auto_20171114_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='payer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PayerGroup', verbose_name='กลุ่ม Payer'),
        ),
    ]
