# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 19:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_auto_20171114_1641'),
        ('core', '0066_product_service_code'),
    ]

    operations = [
    ]
