# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auto_20171115_0931'),
        ('core', '0068_merge_20171114_1901'),
    ]

    operations = [
    ]
