# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_merge_20171115_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ชื่อ Payer แบบสั้น'),
        ),
    ]
