# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_auto_20171115_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='staging_code',
            field=models.CharField(blank=True, help_text='รหัสสิทธิสำหรับส่ง staging', max_length=6),
        ),
    ]
