# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-22 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_auto_20171121_1543'),
        ('core', '0074_productfiltergroup'),
    ]

    operations = [
    ]
