# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_merge_20171122_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoveragePayerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_id', models.CharField(max_length=50, verbose_name='รหัสผู้จ่ายเงิน')),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_payer', to='core.Coverage', verbose_name='สิทธิผู้ป่วย')),
                ('map_to_coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_payer_map', to='core.Coverage', verbose_name='สิทธิผู้ป่วยที่เลือกให้')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='coveragepayermap',
            unique_together=set([('coverage', 'payer_id')]),
        ),
    ]
