# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20171123_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forward_relation', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ความสัมพันธ์ระหว่าง base ไปยัง related patient')),
                ('backward_relation', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ความสัมพันธ์ระหว่าง related ไปยัง base patient')),
                ('base_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_base_patient', to='core.Patient')),
                ('related_patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_related_patient', to='core.Patient')),
            ],
        ),
    ]
