# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 10:41
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_patientrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrelation',
            name='backward_relation',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ความสัมพันธ์ระหว่าง related ไปยัง base patient เช่น related(ช) มี base(ญ) เป็น ภรรยา'),
        ),
        migrations.AlterField(
            model_name='patientrelation',
            name='forward_relation',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, verbose_name='ความสัมพันธ์ระหว่าง base ไปยัง related patient เช่น base(ญ) มี related(ช) เป็น สามี'),
        ),
    ]
