# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_auto_20171127_1027'),
        ('core', '0078_auto_20171127_1041'),
    ]

    operations = [
    ]
