# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-28 14:57
from __future__ import unicode_literals

from django.core.management import call_command
from django.db import migrations, models
import django.db.models.deletion


def load_new_fixture(apps, schema_editor):
    call_command('loaddata', 'assuretype')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_merge_20171127_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('-is_active', 'display_seq'),
            },
        ),
        migrations.RunPython(load_new_fixture),
        migrations.RemoveField(
            model_name='encountercoverage',
            name='assure_type',
        ),
        migrations.RemoveField(
            model_name='patientcoverage',
            name='assure_type',
        ),
        migrations.AddField(
            model_name='encountercoverage',
            name='assure_type',
            preserve_default=False,
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssureType', verbose_name='ประเภทการรับรองสิทธิ์', default=1),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='assure_type',
            preserve_default=False,
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AssureType', verbose_name='ประเภทการรับรองสิทธิ์', default=1),
        ),
    ]
