# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-29 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20171128_1624'),
        ('core', '0080_auto_20171128_1457'),
    ]

    operations = [
    ]
