# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_merge_20171129_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationTypeChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'ประเภทการรักษา',
                'verbose_name': 'ประเภทการรักษา',
            },
        ),
        migrations.AddField(
            model_name='encounter',
            name='examination_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ExaminationTypeChoice'),
        ),
    ]
