# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_coveragedocument_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragedocument',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
