# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20171201_1431'),
        ('core', '0084_coveragedocument_title'),
    ]

    operations = [
    ]
