# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0085_merge_20171204_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='order_ack_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้รับทราบคำสั่ง'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_ack_div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division', verbose_name='แผนกที่รับทราบคำสั่ง'),
        ),
        migrations.AddField(
            model_name='doctororder',
            name='order_ack_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลารับทราบคำสั่ง'),
        ),
    ]
