# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20171204_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='pre_name_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อภาษาอังกฤษ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pre_name_th',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.Prename', verbose_name='คำนำหน้าชื่อภาษาไทย'),
        ),
    ]
