# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20171212_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
