# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0088_auto_20171214_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='printlog',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='printlog',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
