# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_banktransferschedule_banktransferstopschedule'),
        ('core', '0089_auto_20171221_1037'),
    ]

    operations = [
    ]
