# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_merge_20171221_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrelation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
