# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_patientrelation_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferstopschedule',
            name='date',
            field=models.DateField(verbose_name='วันหยุดตามประเพณี'),
        ),
    ]
