# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-27 10:43
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.models import Count


def check_no_duplicate_doctor_code(apps, schema_editor):
    Doctor = apps.get_model('core', 'Doctor')
    duplicate_doctors = list(Doctor.objects.values('code').annotate(Count('id')).order_by().filter(id__count__gt=1))
    if duplicate_doctors:
        msg = 'Migration failed: found following Doctors with duplicate doctor code:\n'
        for doc in duplicate_doctors:
            msg += doc['code'] + '\n'
        msg += 'Please fix the data and try migration again'
        raise Exception(msg)

def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_auto_20171222_1429'),
    ]

    operations = [
        migrations.RunPython(check_no_duplicate_doctor_code, reverse_code=do_nothing),
        migrations.AddField(
            model_name='doctor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='code',
            field=models.CharField(help_text='รหัสแพทย์', max_length=10, unique=True),
        ),
    ]
