# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-04 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_auto_20171227_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Product')),
                ('duration', models.PositiveIntegerField(default=1, help_text='อายุของ package (วัน)')),
                ('can_discount', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Coverage')),
            ],
            options={
                'verbose_name': 'แพ็กเกจ',
            },
            bases=('core.product',),
        ),
    ]
