# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_auto_20180104_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncycle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
