# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_progressioncycle_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounteractionlog',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
