# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_encounteractionlog_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
