# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_product_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_active',
            new_name='active_flag',
        ),
    ]
