# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_procedure_active'),
        ('core', '0100_auto_20180112_1623'),
    ]

    operations = [
    ]
