# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_packageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='encountercoverage',
            name='patient_coverage',
            field=models.ForeignKey(blank=True, help_text='reference PatientCoverage that create this EncounterCoverage.', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.PatientCoverage'),
        ),
    ]
