# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_encountercoverage_patient_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageorder',
            name='patient_coverage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.PatientCoverage'),
        ),
    ]
