# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_auto_20180118_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Episode', verbose_name='Episode of care'),
        ),
    ]
