# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 17:13
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_hospitalfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalfee',
            name='status',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1),
        ),
    ]
