# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_auto_20180125_1713'),
        ('core', '0105_auto_20180126_1656'),
    ]

    operations = [
    ]
