# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_merge_20180126_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='marriage',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('M', 'Married'), ('E', 'Engaged'), ('D', 'Divorced'), ('W', 'Widowed'), ('A', 'Separated')], default='S', max_length=1, verbose_name='สถานภาพ'),
        ),
    ]
