# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_auto_20180129_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardAdministrationTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-is_active', 'display_seq'),
                'abstract': False,
            },
        ),
    ]
