# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-14 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_standardadministrationtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planitem',
            name='actual_orders',
            field=models.ManyToManyField(blank=True, help_text='PlanItem ที่ ผูกกับ DoctorOrder ที่ถูก Clone', related_name='created_from_plan_items', to='core.DoctorOrder', verbose_name='รายการที่ถูกสร้างแล้ว'),
        ),
    ]
