# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_standardadministrationtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='receive_documents',
            field=models.BooleanField(default=False, verbose_name='ต้องการรับเอกสาร'),
        ),
    ]
