# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_merge_20180215_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gazetteers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2, unique=True)),
                ('country_name', models.CharField(max_length=50)),
                ('region', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('zipcode', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'GAZETTEERS',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='district',
            name='code',
        ),
        migrations.RemoveField(
            model_name='province',
            name='code',
        ),
    ]
