# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-20 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20180220_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='province',
            name='name_en',
            field=models.CharField(max_length=50),
        ),
    ]
