# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


def copy_perform_datetime_to_charges_date(apps, schema_editor):
    MiscellaneousOrder = apps.get_model('core', 'MiscellaneousOrder')
    miscellaneous_orders = MiscellaneousOrder.objects.all()
    for miscellaneous_order in miscellaneous_orders:
        miscellaneous_order.charges_date = miscellaneous_order.perform_datetime.date()
        miscellaneous_order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_auto_20180306_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousorder',
            name='charges_date',
            field=models.DateField(default=datetime.date.today, help_text='วันที่ของค่าใช้จ่าย จะแสดงใบใบรายละเอียดใบเสร็จ'),
        ),
        migrations.RunPython(copy_perform_datetime_to_charges_date, lambda: None),
    ]
