# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-15 11:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_miscellaneousorder_charges_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='division',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.Department', verbose_name='ภาควิชาที่หน่วยงานนี้สังกัด'),
        ),
        migrations.AlterField(
            model_name='division',
            name='parent',
            field=his.framework.models.fields.SelfReferenceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Division'),
        ),
        migrations.AddField(
            model_name='division',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.CostCenter', verbose_name='หน่วยต้นทุนที่ผูกกับหน่วยงานนี้'),
        ),
    ]
