# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_auto_20180315_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousorder',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='a quantity of product to be charged', max_digits=10),
        ),
    ]
