# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_auto_20180319_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
