# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-04 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20180320_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('alias', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'ordering': ('-is_active', 'display_seq'),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='division',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='core.Area', verbose_name='ที่ตั้งของหน่วยงาน'),
        ),
    ]
