# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-04 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_auto_20180320_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardAdministrationTimeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('standard_admin_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.StandardAdministrationTime')),
            ],
        ),
    ]
