# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-09 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_merge_20180404_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardadministrationtime',
            name='omission_time',
            field=models.IntegerField(default=60, help_text='จำนวนนาทีสูงสุดที่สามารถให้ยาคลาดเคลื่อนได้'),
        ),
    ]
