# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 18:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0120_merge_20180404_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('datetime', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('related_issue_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_issue_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Stock')),
            ],
        ),
    ]
