# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-10 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_standardadministrationtime_omission_time'),
        ('core', '0121_stocklog'),
    ]

    operations = [
    ]
