# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_merge_20180417_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverage',
            name='approval_code_required',
            field=models.BooleanField(default=False, help_text='สิทธิ์นี้จำเป็นต้องกรอก Approval Code ที่แผนกการเงินหรือไม่'),
        ),
    ]
