# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-17 17:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0126_auto_20180504_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.PositiveIntegerField()),
                ('target_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recordlocker',
            unique_together=set([('target_type', 'target_id')]),
        ),
    ]
