# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20180517_1729'),
        ('core', '0127_auto_20180517_1648'),
    ]

    operations = [
    ]
