# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 14:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_auto_20180517_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='description',
            field=models.TextField(blank=True, verbose_name='รายละเอียด'),
        ),
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='ชื่อ Episode of care'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='วันเริ่มต้น Episode'),
            preserve_default=False,
        ),
    ]
