# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_merge_20180518_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanneddocument',
            old_name='date',
            new_name='scanned_date',
        ),
    ]
