# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20180518_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='document_date',
            field=models.DateField(default=datetime.date.today, verbose_name='วันที่ของเอกสาร'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='document_no',
            field=models.CharField(blank=True, max_length=50, verbose_name=''),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='expired_date',
            field=models.DateField(null=True, verbose_name='วันหมดอายุ'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='owner_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division', verbose_name='แผนกเจ้าของเอกสาร'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='remark',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='scan_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Division', verbose_name='แผนกที่สแกนเอกสาร'),
        ),
        migrations.AddField(
            model_name='scanneddocument',
            name='version',
            field=models.IntegerField(default=1, verbose_name='version เอกสาร'),
        ),
    ]
