# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_auto_20180518_1304'),
        ('core', '0128_auto_20180518_1443'),
    ]

    operations = [
    ]
