# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_merge_20180518_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanneddocument',
            old_name='expired_date',
            new_name='expiry_date',
        ),
        migrations.RenameField(
            model_name='scanneddocument',
            old_name='scanned_date',
            new_name='scan_date',
        ),
    ]
