# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0132_auto_20180518_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='scan_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สแกนเอกสาร'),
        ),
    ]
