# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-21 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_scanneddocument_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardadministrationtimeitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
