# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_standardadministrationtimeitem_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressioncycle',
            name='creator',
            field=models.ForeignKey(help_text='Ordered doctor', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Doctor'),
        ),
    ]
