# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def create_default_procession_cycle_creator(apps, schema_editor):
    ProgressionCycle = apps.get_model('core', 'ProgressionCycle')
    for cycle in ProgressionCycle.objects.all():
        cycle.creator = cycle.emr.doctor
        cycle.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_progressioncycle_creator'),
    ]

    operations = [
        migrations.RunPython(
            create_default_procession_cycle_creator,
            reverse_code=lambda apps,
            schema_editor: None,
        ),
        migrations.AlterField(
            model_name='progressioncycle',
            name='creator',
            field=models.ForeignKey(help_text='Ordered doctor', on_delete=django.db.models.deletion.CASCADE, to='core.Doctor'),
        ),
    ]
