# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-22 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_auto_20180521_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanneddocument',
            name='cancel_note',
            field=models.TextField(blank=True, verbose_name='หมายเหตุการยกเลิก'),
        ),
    ]
