# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_scanneddocument_cancel_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanneddocument',
            options={'permissions': (('can_edit_scanned_document', 'Can edit ScannedDocument'), ('can_cancel_scanned_document', 'Can cancel ScannedDocument')), 'verbose_name': 'ภาพสแกนเอกสารผู้ป่วย'},
        ),
    ]
