# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-23 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0138_auto_20180523_1700'),
        ('core', '0138_auto_20180523_1559'),
    ]

    operations = [
    ]
