# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-24 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0139_merge_20180523_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อกลุ่ม')),
                ('doctors', models.ManyToManyField(to='core.Doctor', verbose_name='แพทย์ในกลุ่ม')),
            ],
            options={
                'verbose_name': 'กลุ่มแพทย์',
                'verbose_name_plural': 'กลุ่มแพทย์',
            },
        ),
    ]
