# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-06-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0140_doctorgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='planitem',
            name='realize_every_time',
            field=models.BooleanField(default=False),
        ),
    ]
