# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-19 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_planitem_realize_every_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='common',
            field=models.BooleanField(default=False, verbose_name='เป็นแพทย์กลางหรือไม่'),
        ),
    ]
