# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-20 12:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_auto_20180614_1103'),
        ('core', '0142_doctor_common'),
    ]

    operations = [
    ]
