# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-08 10:51
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields
from his.core.models import Procedure as CORE_PROCEDURE
SOURCE = CORE_PROCEDURE.SOURCE


def change_procedure_source_to_trt(apps, schema_editor):
    Procedure = apps.get_model('core', 'Procedure')
    for procedure in Procedure.objects.filter(source=SOURCE.UNKNOWN):
        procedure.source = SOURCE.TREATMENT
        procedure.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0143_merge_20180620_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='source',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1, verbose_name='ชนิดของ Procedure'),
        ),
        migrations.RunPython(
            code=change_procedure_source_to_trt,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
