# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 11:38
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


def fill_diagnosis_source(apps, schema_editor):
    Diagnosis = apps.get_model('core', 'Diagnosis')

    ENCOUNTER_TYPE_OPD = 'OPD'
    ENCOUNTER_TYPE_IPD = 'IPD'
    ENCOUNTER_TYPE_SS = 'SS'
    ENCOUNTER_TYPE_ER = 'ER'
    ENCOUNTER_IPD_TYPES = [ENCOUNTER_TYPE_IPD]
    ENCOUNTER_OPD_TYPES = [ENCOUNTER_TYPE_OPD, ENCOUNTER_TYPE_ER, ENCOUNTER_TYPE_SS]

    PRIMARY = 1
    SECONDARY = 2
    PROVISIONAL_PRIMARY = 3
    PROVISIONAL_SECONDARY_COMORBID = 4
    PROVISIONAL_SECONDARY_COMPLICATION = 5
    PROVISIONAL_SECONDARY_OTHER = 6
    SECONDARY_COMORBID = 7
    SECONDARY_COMPLICATION = 8
    SECONDARY_OTHER = 9
    DIAGNOSIS_IPD_LIST = [
        PROVISIONAL_PRIMARY,
        PROVISIONAL_SECONDARY_COMORBID,
        PROVISIONAL_SECONDARY_COMPLICATION,
        PROVISIONAL_SECONDARY_OTHER,
        SECONDARY_COMORBID,
        SECONDARY_COMPLICATION,
        SECONDARY_OTHER,
    ]
    SOURCE_OPD = 1
    SOURCE_IPD = 2

    Diagnosis.objects.filter(
        type__in=[PRIMARY, SECONDARY],
        emr__encounter__type__in=ENCOUNTER_OPD_TYPES
    ).update(source=SOURCE_OPD)

    Diagnosis.objects.filter(
        type=PRIMARY,
        emr__encounter__type__in=ENCOUNTER_IPD_TYPES
    ).update(source=SOURCE_IPD)

    Diagnosis.objects.filter(type__in=DIAGNOSIS_IPD_LIST).update(source=SOURCE_IPD)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0144_procedure_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='source',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1, verbose_name='ชนิดของ Diagnosis'),
        ),
        migrations.RunPython(fill_diagnosis_source, reverse_code=migrations.RunPython.noop),
    ]
