# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-10 15:27
from __future__ import unicode_literals

from django.db import migrations
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_diagnosis_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='source',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1, verbose_name='แหล่งที่มาของ Procedure'),
        ),
    ]
