# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-16 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_auto_20180810_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcoverage',
            name='claim_code_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่หมดอายุเลข e-claim'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='claim_code_expiry_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่หมดอายุเลข e-claim'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='claim_code_request_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่ขอเลข e-claim'),
        ),
        migrations.AddField(
            model_name='patientcoverage',
            name='claim_code_request_time',
            field=models.TimeField(blank=True, null=True, verbose_name='เวลาที่ขอเลข e-claim'),
        ),
    ]
