# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-31 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20180816_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(null=True, upload_to='core/department/logo/'),
        ),
    ]
