# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-12 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_auto_20180816_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='core_procedure', to='core.DoctorOrder', verbose_name='Doctor Order'),
        ),
    ]
