# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 12:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_auto_20180912_1710'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='icd10',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='icd10medicalterm',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='icd9cm',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='icd9cmmedicalterm',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
