# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-19 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20181011_1208'),
        ('core', '0148_department_logo'),
    ]

    operations = [
    ]
