# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-18 12:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_auto_20181011_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctororder',
            name='is_advance',
            field=models.BooleanField(default=False, verbose_name='คำสั่งล่วงหน้า'),
        ),
    ]
