# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-12-11 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_merge_20181119_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specialty',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialty',
            field=models.ManyToManyField(blank=True, to='core.Specialty'),
        ),
    ]
