# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_doctororder_is_advance'),
        ('core', '0151_auto_20190531_1559'),
    ]

    operations = [
    ]
