# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-14 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190114_1040'),
        ('core', '0152_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivisionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Division')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Location')),
            ],
            options={
                'verbose_name': 'สถานที่ตั้งหน่วยงาน',
                'verbose_name_plural': 'สถานที่ตั้งหน่วยงาน',
            },
        ),
    ]
