# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_divisionlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
