# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_language_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
