# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 17:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0155_doctor_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Action',
            },
        ),
        migrations.CreateModel(
            name='UnitSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveIntegerField()),
                ('start_datetime', models.DateTimeField(verbose_name='วันเวลาเริ่มต้น')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='วันเวลาสิ้นสุด')),
                ('status', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=0, verbose_name='สถานะของ Unit')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('allowed_actions', models.ManyToManyField(to='core.Action', verbose_name='Action ที่สามารถทำได้')),
                ('change_status_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Action', verbose_name='Action ที่ทำให้ Unit เปลี่ยนสถานะ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Unit Slot',
                'verbose_name_plural': 'Unit Slot',
            },
        ),
    ]
