# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_doctor_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
