# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_department_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='core/department/logo/'),
        ),
    ]
