# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_auto_20190214_1216'),
        ('core', '0156_action_unitslot'),
    ]

    operations = [
    ]
