# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-14 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_merge_20190214_1806'),
        ('core', '0158_merge_20190214_1747'),
    ]

    operations = [
    ]
