# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-20 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_auto_20190220_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unit Status',
                'verbose_name_plural': 'Unit Status',
            },
        ),
        migrations.CreateModel(
            name='UnitStatusAllowedAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='unitaction',
            options={'verbose_name': 'Unit Action', 'verbose_name_plural': 'Unit Action'},
        ),
        migrations.RemoveField(
            model_name='unitslot',
            name='status',
        ),
        migrations.AddField(
            model_name='unitaction',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='unitslot',
            name='allowed_actions',
            field=models.ManyToManyField(help_text='derived from UnitStatusAllowedAction', to='core.UnitAction', verbose_name='Action ที่สามารถทำได้'),
        ),
        migrations.AlterField(
            model_name='unitslot',
            name='change_status_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.UnitAction', verbose_name='UnitAction ที่ทำให้ Unit เปลี่ยนสถานะ'),
        ),
        migrations.AddField(
            model_name='unitstatusallowedaction',
            name='allowed_actions',
            field=models.ManyToManyField(to='core.UnitAction', verbose_name='Action ที่สามารถทำได้'),
        ),
        migrations.AddField(
            model_name='unitstatusallowedaction',
            name='unit_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UnitStatus'),
        ),
        migrations.AddField(
            model_name='unitslot',
            name='unit_status',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.UnitStatus', verbose_name='สถานะของ Unit'),
            preserve_default=False,
        ),
    ]
