# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-25 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_auto_20190221_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='image',
            field=models.ImageField(max_length=150, null=True, upload_to=''),
        ),
    ]
