# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_unit_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to=''),
        ),
    ]
