# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0164_auto_20190227_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='code',
            field=models.CharField(help_text='an abbreviation of the unit of measure', max_length=100, unique=True),
        ),
    ]
