# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-04 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0165_auto_20190304_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='doctors/', verbose_name='doctor image file'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='image_url',
            field=models.URLField(help_text='this will override image field', null=True, verbose_name='doctor image url'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='core/medication/icons/'),
        ),
    ]
