# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0166_auto_20190304_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image',
            field=models.ImageField(null=True, upload_to='doctors/images/', verbose_name='doctor image file'),
        ),
    ]
