# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-14 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0167_auto_20190308_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='pre_name_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Prename'),
        ),
        migrations.AddField(
            model_name='specialty',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='ชื่อของตัวเลือก en'),
        ),
    ]
