# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0169_doctorboard_doctorcertification_doctoreducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitslot',
            name='allowed_actions',
            field=models.ManyToManyField(blank=True, help_text='derived from UnitStatusAllowedAction', to='core.UnitAction', verbose_name='Action ที่สามารถทำได้'),
        ),
    ]
