# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-05-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0170_auto_20190320_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
