# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20190522_1125'),
        ('core', '0153_auto_20190808_1634'),
    ]

    operations = [
    ]
