# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0172_auto_20190522_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hn',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='หมายเลข HN'),
        ),
    ]
