# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-06-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0173_auto_20190607_0946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ชื่อของตัวเลือก')),
                ('display_seq', models.IntegerField(default=999, verbose_name='ลำดับการแสดงผลบนหน้าจอ')),
                ('is_active', models.BooleanField(default=True)),
                ('name_en', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('TH', 'Thai'), ('EN', 'English')], default='TH', max_length=2)),
            ],
            options={
                'ordering': ['display_seq'],
            },
        ),
        migrations.AddField(
            model_name='nationality',
            name='language',
            field=models.CharField(choices=[('TH', 'Thai'), ('EN', 'English')], default='TH', max_length=2),
        ),
    ]
