# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-22 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0174_auto_20190612_1709'),
        ('core', '0173_merge_20190821_1658'),
    ]

    operations = [
    ]
