# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PgtIOU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pgtIou', models.CharField(max_length=255, unique=True, verbose_name='proxy ticket IOU')),
                ('tgt', models.CharField(max_length=255, verbose_name='ticket granting ticket')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'proxy ticket IOUs',
                'verbose_name': 'proxy ticket IOU',
                'db_table': 'django_cas_pgtiou',
            },
        ),
        migrations.CreateModel(
            name='SessionServiceTicket',
            fields=[
                ('service_ticket', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='service ticket')),
                ('session_key', models.CharField(max_length=40, verbose_name='session key')),
            ],
            options={
                'verbose_name_plural': 'session service tickets',
                'verbose_name': 'session service ticket',
                'db_table': 'django_cas_session_service_ticket',
            },
        ),
        migrations.CreateModel(
            name='Tgt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='username')),
                ('tgt', models.CharField(max_length=255, verbose_name='ticket granting ticket')),
            ],
            options={
                'verbose_name_plural': 'ticket granting tickets',
                'verbose_name': 'ticket granting ticket',
                'db_table': 'django_cas_tgt',
            },
        ),
    ]
