# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('curator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorChannel'),
        ),
        migrations.AddField(
            model_name='provider',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='provider',
            name='provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.ProviderType'),
        ),
        migrations.AddField(
            model_name='premise',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Address'),
        ),
        migrations.AddField(
            model_name='premise',
            name='premise_images',
            field=models.ManyToManyField(blank=True, to='appointment.PremiseImage'),
        ),
        migrations.AddField(
            model_name='extraservicedetail',
            name='service_appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.ServiceAppointment'),
        ),
        migrations.AddField(
            model_name='extraservicedetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='compositechannel',
            name='main_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composite', to='curator.CuratorChannel'),
        ),
        migrations.AddField(
            model_name='compositechannel',
            name='member_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_composite', to='curator.CuratorChannel'),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Appointment'),
        ),
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='provider_available_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.ProviderAvailableSlot'),
        ),
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='user_available_slot',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.UserAvailableSlot'),
        ),
        migrations.AddField(
            model_name='appointmenttype',
            name='provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.ProviderType'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.Address'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='invitee',
            field=models.ManyToManyField(related_name='invitee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.AppointmentType'),
        ),
        migrations.AlterUniqueTogether(
            name='usercaddypremise',
            unique_together=set([('caddy', 'premise')]),
        ),
        migrations.AlterUniqueTogether(
            name='appointmentusertimeslot',
            unique_together=set([('appointment', 'user', 'timeslot')]),
        ),
        migrations.AlterUniqueTogether(
            name='appointmenttype',
            unique_together=set([('name', 'provider_type')]),
        ),
    ]
