# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-11 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20181005_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='provideravailableslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='useravailableslot',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provideravailableslot',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_slot', to='appointment.Provider'),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='category',
            field=models.CharField(choices=[('na', 'na'), ('caddy', 'caddy'), ('technician', 'technician'), ('golf_course', 'golf_course'), ('customer_house', 'customer_house'), ('division', 'division')], default='na', max_length=32),
        ),
    ]
