# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-17 12:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('curator', '0002_remove_userdetail_date_joined'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0004_auto_20181011_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientServiceSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_slot', models.IntegerField(default=0)),
                ('end_slot', models.IntegerField(default=0)),
                ('status', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ClientType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('na', 'na'), ('division', 'division')], default='na', max_length=32)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='วันที่เริ่มต้นบันทึก')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด')),
                ('status', his.framework.models.fields._StatableStatusField(default=0, editable=False)),
                ('client_service_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.ClientServiceSlot')),
                ('edit_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ตารางเวร',
            },
        ),
        migrations.RemoveField(
            model_name='client',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.RemoveField(
            model_name='client',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='tel',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.RemoveField(
            model_name='provideravailableslot',
            name='active',
        ),
        migrations.AddField(
            model_name='client',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorChannel'),
        ),
        migrations.AddField(
            model_name='client',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provideravailableslot',
            name='status',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, default=1),
        ),
        migrations.AlterField(
            model_name='providertype',
            name='category',
            field=models.CharField(choices=[('na', 'na'), ('caddy', 'caddy'), ('technician', 'technician'), ('golf_course', 'golf_course'), ('customer_house', 'customer_house'), ('nurse', 'nurse')], default='na', max_length=32),
        ),
        migrations.AddField(
            model_name='providerassign',
            name='provider_available_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.ProviderAvailableSlot'),
        ),
        migrations.AddField(
            model_name='clientserviceslot',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_slot', to='appointment.Client'),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.ClientType'),
            preserve_default=False,
        ),
    ]
