# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-22 09:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointment', '0005_auto_20181017_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAssignActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Provider Assign Action Log',
                'verbose_name_plural': 'Provider Assign Action Log',
            },
        ),
        migrations.AddField(
            model_name='clientserviceslot',
            name='slot',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clientserviceslot',
            name='type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideravailableslot',
            name='slot',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideravailableslot',
            name='type',
            field=his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='providerassign',
            name='provider_available_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assign_provider_slot', to='appointment.ProviderAvailableSlot'),
        ),
        migrations.AddField(
            model_name='providerassignactionlog',
            name='statable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='appointment.ProviderAssign'),
        ),
        migrations.AddField(
            model_name='providerassignactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
