# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_auto_20181126_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='timeslot_end',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
