# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-28 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_appointmentusertimeslot_timeslot_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='serviceappointment',
            name='business',
        ),
        migrations.DeleteModel(
            name='BusinessDetail',
        ),
    ]
