# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-29 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('appointment', '0010_auto_20181128_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specific_type',
            field=models.ForeignKey(editable=False, help_text='specific type of business logic', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
