# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-01-30 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0019_auto_20190118_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentusertimeslot',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_timeslot', to='appointment.Appointment'),
        ),
    ]
