# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-08 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0022_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='service_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remark_sa', to='appointment.ServiceAppointment'),
        ),
    ]
