# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0023_remark_service_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentusertimeslot',
            name='status',
            field=models.CharField(blank=True, default='', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='remark',
            name='key',
            field=models.CharField(max_length=40),
        ),
    ]
