# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-02-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0024_auto_20190211_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='service_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sa_timeslot', to='appointment.ServiceAppointment'),
        ),
    ]
