# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_auto_20190419_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceappointment',
            name='client',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviceappointment',
            name='provider',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='appointment.Provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='swapshiftbroadcast',
            name='source_provider_assign',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='source_pa', to='appointment.ProviderAssign'),
            preserve_default=False,
        ),
    ]
