# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-26 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0029_auto_20190423_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentusertimeslot',
            name='provider_assign',
        ),
        migrations.AddField(
            model_name='appointmentusertimeslot',
            name='provider_assigns',
            field=models.ManyToManyField(blank=True, null=True, related_name='app_provider_assign', to='appointment.ProviderAssign'),
        ),
    ]
