# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorChannelSuggestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_id', models.CharField(max_length=50)),
                ('index', models.IntegerField()),
                ('suggest_datetime', models.DateTimeField()),
                ('curatorChannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorChannel')),
            ],
        ),
        migrations.CreateModel(
            name='CuratorSupportMapper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('epg_name', models.CharField(max_length=200, verbose_name='EPG Name')),
                ('epg_channel_id', models.CharField(max_length=200, verbose_name='EPG ChannelId')),
                ('match_with', models.IntegerField(choices=[(1, 'EPG Name'), (2, 'EPG Channel Id')], default=1)),
                ('curatorSupport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorSupport', verbose_name='Live Channel')),
            ],
        ),
        migrations.CreateModel(
            name='EPGSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.IntegerField(choices=[(1, 'Sanook'), (2, 'True Vision')], default=1)),
                ('url', models.CharField(max_length=500)),
                ('enabled', models.BooleanField(default=True)),
                ('curatorSupport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorSupport', verbose_name='Live Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('detail', models.TextField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('start_datetime', models.DateTimeField()),
                ('duration', models.IntegerField(help_text='minute')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveSuggestLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_id', models.CharField(max_length=50)),
                ('index', models.IntegerField()),
                ('suggest_datetime', models.DateTimeField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppg.Episode')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Program Name')),
                ('detail', models.TextField(blank=True, max_length=2000, null=True)),
                ('icon', models.ImageField(blank=True, upload_to='uploaded/support', verbose_name='Icon')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('new_program', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('curatorSupport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorSupport', verbose_name='Live Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')], default=1)),
                ('start_time', models.TimeField()),
                ('duration', models.IntegerField(help_text='minute')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppg.Program')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppg.Program'),
        ),
    ]
