# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-14 10:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import his.framework.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HRM', '0029_swapshiftrequest_broadcast'),
        ('sqool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChatSubscriptionActionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', his.framework.models.fields.EnumField(his.framework.models.fields._DummyEnum)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_chat_channel', to='HRM.Client'),
        ),
        migrations.AddField(
            model_name='userchatsubscription',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='วันที่เริ่มต้นบันทึก'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userchatsubscription',
            name='edit_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='userchatsubscription',
            name='edited',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
        migrations.AddField(
            model_name='userchatsubscription',
            name='map_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userchatsubscription',
            name='status',
            field=his.framework.models.fields._StatableStatusField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='userchatsubscriptionactionlog',
            name='statable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='sqool.UserChatSubscription'),
        ),
        migrations.AddField(
            model_name='userchatsubscriptionactionlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
