# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-09 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqool', '0004_auto_20190327_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content_type',
            field=models.CharField(choices=[('text', 'text'), ('image', 'image'), ('video', 'video'), ('file', 'file'), ('swap', 'swap'), ('activity', 'activity')], max_length=10),
        ),
    ]
