# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-09 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='date_joined',
        ),
    ]
