# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoopVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('video_type', models.CharField(choices=[('Y', 'Youtube'), ('F', 'Facebook'), ('D', 'Dailymotion'), ('V', 'Vimeo'), ('E', 'etc'), ('S', 'Stream URL'), ('M', 'M3U8'), ('R', 'RTMP'), ('T', 'RTSP')], max_length=1)),
                ('video_id', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail_url', models.CharField(max_length=200)),
                ('isAvailable', models.BooleanField(default=True)),
                ('payload', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
