# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploaded/wallpaper', verbose_name='Image')),
                ('image_H3', models.ImageField(blank=True, null=True, upload_to='uploaded/wallpaper', verbose_name='Image H3 Common')),
                ('image_H3_inter', models.ImageField(blank=True, null=True, upload_to='uploaded/wallpaper', verbose_name='Image H3 Overseas')),
                ('published', models.DateTimeField(blank=True, default=None, help_text='The last time this wallpaper had been published. Set this field blank to show this wallpaper tomorrow.', null=True, verbose_name='โชว์บนทีวีครั้งล่าสุด')),
                ('start_publish_date', models.DateTimeField(blank=True, default=None, help_text='วันที่ให้เริ่มโชว์ภาพนี้ ควรกำหนดเวลาเป็น 0:00', null=True)),
                ('end_publish_date', models.DateTimeField(blank=True, default=None, help_text='วันสุดท้ายที่ให้โชว์ภาพนี้ ควรกำหนดเวลาเป็น 0:00', null=True)),
                ('isHighPriority', models.BooleanField(default=False, help_text='Wallpaper ที่เป็น promotion จะถูกเลือกใช้ ก่อน Wallpaper อื่นๆ ในช่วงวันที่เดียวกัน', verbose_name='Promotion')),
            ],
            options={
                'get_latest_by': 'published',
                'ordering': ['published'],
            },
        ),
    ]
