# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from his.penta.showtime import utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratorSuggestedLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_done', models.BooleanField(default=False)),
                ('detail', models.CharField(blank=True, max_length=2000, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_links', to='curator.CuratorChannel')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorLink')),
                ('suggested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='FacebookUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('facebook_user_id', models.CharField(blank=True, max_length=200, null=True)),
                ('latest_query_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeedEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('video_position', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('D', 'Draft'), ('R', 'Ready'), ('S', 'Sent'), ('O', 'Old'), ('X', 'Deleted')], default='D', max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorChannel')),
                ('playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curator.CuratorPlaylist')),
            ],
        ),
        migrations.CreateModel(
            name='FeedEmailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=utils.UploadToDir('uploaded/email'))),
                ('position', models.IntegerField(default=0)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='feed.FeedEmail')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FeedEmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mini_preview', models.ImageField(upload_to=utils.UploadToDir('uploaded/email_templates'))),
                ('media_num', models.IntegerField(default=0)),
                ('file', models.FileField(upload_to=utils.UploadToDir('uploaded/email_templates'))),
            ],
        ),
        migrations.AddField(
            model_name='feedemail',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feed.FeedEmailTemplate'),
        ),
        migrations.AddField(
            model_name='feedemail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
