# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-05 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_function', models.TextField(blank=True, default='', help_text='python code can access feature check results with `args[x]` and must set variable `result` before code ended.`result` must be boolean.')),
                ('enabled', models.BooleanField(default=True)),
                ('target_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tag_decision', to='curator.CuratorTag')),
            ],
        ),
        migrations.CreateModel(
            name='TagFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('M', 'matched text'), ('T', 'has tag')], max_length=1)),
                ('argument', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(blank=True)),
                ('tag_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='videos_tagging.TagDecision')),
            ],
            options={
                'ordering': ['tag_decision', 'order'],
            },
        ),
    ]
