# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0027_auto_20190419_0946'),
        ('sqool', '0005_auto_20190409_1111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatchannel',
            name='client'
        ),
        migrations.AddField(
            model_name='chatchannel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_chat_channel', to='appointment.Client'),
        ),
    ]
