# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-19 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sqool', '0006_auto_20190419_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchatsubscription',
            name='schedule_color',
            field=models.CharField(blank=True, null=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='content_payload',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
